import = [ "/home/rudro/.config/alacritty/themes/themes/carbonfox.toml" ]

# Bright colors
[colors.bright]
black   = '#686868'

[font]
size = 11.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"
