format = """$all|$os
$character"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[line_break]
disabled = true

[os]
disabled = false

[os.symbols]
Windows = "  "
Linux = "🐧"
Ubuntu = "🐧"
